### ISSUE TITLE
readme - setup instructions

### ISSUE THREAD

**Issue by whatSocks** [enjoysmath/QuiverDatabase#1]
Hello, 
I am interested in running this project - are there any special setup instructions?

**Comment by enjoysmath** [comment]
> Hello,
> I am interested in running this project - are there any special setup instructions?

@whatSocks Hello!  Thank you for your interest.  Right now, there is no reliable Neo4j host being used, so you'll have to host your own Neo4j Desktop database locally.  Later, when we can afford $50 / month for basic [Graphene DB](https://www.graphenedb.com/pricing.html) account, we'll have a server settings page for admins that allows you to set what database to use.   Right now, these settings are part of the WingWare project file if running the project locally, and part of the Heroku Config variables if running there.  If you set up a remote for git (one command) to publish to your heroku app, then the code files are already set up to work on Heroku.  Except there's no reliable Neo4j host set up yet, so you get database connection errors.

If you'd like to use the diagram editor without database support.  Please see: 

https://github.com/varkor/quiver

There's a link on that page that opens a client-side JS application for creating the diagrams.  Sharing is done through encoding the diagram into a URL.

Now I will work on the set up instructions for getting this project to run on your local machine, and hopefully you can help us code the thing.  It's a Django project, so it's Python + JS + HTML + CSS.    We use Bootstrap 3, X-editable, for UI design, and a bunch Django (Python) libraries, listed in requirements.txt.

It should be no more than 1-2 days before I can get all the instructions up.  I will post back here when done so that you get notified.  Again, thank you for your interest!

**Comment by whatSocks** [comment]
Great thank you

**Comment by enjoysmath** [comment]
@whatSocks 

https://github.com/enjoysmath/QuiverDatabase

I am available to help you right now using TeamViewer if you'd like to get together and set up your environment.  Else, please post back here if something doesn't work.

**Comment by whatSocks** [comment]
OK I'll try to get it running locally then come back with any questions. It is a very cool concept.

**Comment by whatSocks** [comment]
@enjoysmath 
my first error:
```
➜  QuiverDatabase git:(main) python manage.py runserver 8000
  File "manage.py", line 17
    ) from exc
         ^
SyntaxError: invalid syntax
```

**Comment by whatSocks** [comment]
I was able to run the app and log in with the test credentials, but my database is empty (so my test user doesn't actually exist?), and when I tap "Create Rule" I get this error:

<img width="996" alt="Screen Shot 2021-01-30 at 1 05 31 PM" src="https://user-images.githubusercontent.com/2731744/106364283-d680a300-62fb-11eb-924d-4d8487135d59.png">

**Comment by enjoysmath** [comment]
@whatSocks that's normal.  It was implemented prior, but then I made some changes to the code.  Regarding your "raise from exc" syntax error in the email.  Make sure you're using Python 3.x.   Do a `where python` to check version and put the 3.x paths first in your Path environment variable so that `where python` lists the Python 3.x install first.

I don't think the SQLite database file (holding the users) is empty which is why you should be able to log in.  This is the current state of things.  So we could use some help clearly!

**Comment by enjoysmath** [comment]
@whatSocks the rule editor is viewable now.  However, rule search currently is not implemented.  Working on that next. 

![image](https://user-images.githubusercontent.com/1606391/107076231-fbfc2980-679f-11eb-8f40-48d1ac7e4126.png)

As you can see each diagram (key / result) of a rule is just a diagram editor iframed into the page (so there are a total of two on the rule editor page).  Within any diagram editor there's now  a "Commutes / Noncommutative" toggle which does write to the database.    Clicking on "Rule Search" pops up the above dialog which is supposed to be a  "search for all rules with key diagram matching your drawn diagram".  Working on that now.

**Comment by enjoysmath** [comment]
@whatSocks 

I got the Rule Search feature to work, so definitely the Rule Editor works by now.  Here is a video of the Rule Search and Rule Apply (with Variable Substitution!):

https://youtu.be/kKJySXo9BDA

**Comment by whatSocks** [comment]
@enjoysmath I'll check it out soon :)

**Comment by enjoysmath** [comment]
@whatSocks I've ceased development on this for now.  I'm instead working on a PyQt5 (desktop app) program for gamifying Category Theory for students.  Perhaps it will also tie into a database, but not sure yet.  I have most of the frontend code already written for the PyQt5 app  (it started as an older project called BananaCats).   You're welcome to work on this QuiverDatabase code if you'd like.

**Comment by enjoysmath** [comment]
@whatSocks I'm going to start back up development of this codebase.   Did you check out the search feature?

**Comment by enjoysmath** [comment]
@whatSocks I'm re-installing everything and trying to get a startup host

**Comment by whatSocks** [comment]
I set up my demo neo4j app  w/ Aura free and a free heroku account if that's helpful

**Comment by enjoysmath** [comment]
> I set up my demo neo4j app w/ Aura free and a free heroku account if that's helpful

What's Aura?  I'm thinking of going with digital ocean.  They're prices are way on the affordable end.

**Comment by enjoysmath** [comment]
> I set up my demo neo4j app w/ Aura free and a free heroku account if that's helpful

Would you like to collaborate with me on this Quiver Database project?  I'm changing the name to AbstractSpacecraft, so there will be another repo up and it's up now, it's just a barebones Django project until I can get the critical parts copied over and OAuth2 working using the oath toolkit.  Ran into some issues last night doing that.
